using System;
using System.Collections.Generic;
using System.Text;

namespace SlipeLua.Shared.Radar
{
    /// <summary>
    /// Represents different icons for map blips
    /// </summary>
    public enum BlipType
    {
        Marker,
        WhiteWquare,
        Centre,
        MapHere,
        North,
        Airyard,
        Gun,
        Barbers,
        BigSmoke,
        Boatyard,
        Burgershot,
        Bulldozer,
        CatPink,
        Cesar,
        Chicken,
        Cj,
        Crash,
        Diner,
        EmmetGun,
        EnemyAttack,
        Fire,
        Girlfriend,
        Hospital,
        Loco,
        MaddDogg,
        Mafia,
        McStrap,
        ModGarage,
        OgLoc,
        Pizza,
        Police,
        PropertyGreen,
        PropertyRed,
        Race,
        Ryder,
        Savehouse,
        School,
        Mystery,
        Sweet,
        Tattoo,
        Truth,
        Waypoint,
        TorenoRanch,
        Triads,
        TriadsCasino,
        TShirt,
        Woozie,
        Zero,
        DateDisco,
        DateDrink,
        DateFood,
        Truck,
        Cash,
        Flag,
        Gym,
        Impound,
        RunwayLight,
        Runway,
        GangB,
        GangP,
        GangY,
        GangN,
        GangG,
        Spray
    }
}
