using System;
using System.Collections.Generic;
using System.Text;

namespace Slipe.Client.Peds
{
    /// <summary>
    /// Represents a PedVoice group and name
    /// </summary>
    public struct PedVoice
    {
        /// <summary>
        /// The group this voice is in
        /// </summary>
        public string Group { get; set; }

        /// <summary>
        /// The name of this voice
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Build a ped voice from a group and name
        /// </summary>
        public PedVoice(string group, string name)
        {
            Group = group;
            Name = name;
        }

        #region Static Properties

        public static PedVoice DISABLED { get { return new PedVoice("PED_TYPE_DISABLED", null); } }
        public static PedVoice GEN_BBDYG1 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BBDYG1"); } }
        public static PedVoice GEN_BBDYG2 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BBDYG2"); } }
        public static PedVoice GEN_BFORI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BFORI"); } }
        public static PedVoice GEN_BFOST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BFOST"); } }
        public static PedVoice GEN_BFYBE { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BFYBE"); } }
        public static PedVoice GEN_BFYBU { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BFYBU"); } }
        public static PedVoice GEN_BFYCRP { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BFYCRP"); } }
        public static PedVoice GEN_BFYPRO { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BFYPRO"); } }
        public static PedVoice GEN_BFYRI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BFYRI"); } }
        public static PedVoice GEN_BFYST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BFYST"); } }
        public static PedVoice GEN_BIKDRUG { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BIKDRUG"); } }
        public static PedVoice GEN_BIKERA { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BIKERA"); } }
        public static PedVoice GEN_BIKERB { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BIKERB"); } }
        public static PedVoice GEN_BMOCD { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BMOCD"); } }
        public static PedVoice GEN_BMORI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BMORI"); } }
        public static PedVoice GEN_BMOSEC { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BMOSEC"); } }
        public static PedVoice GEN_BMOST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BMOST"); } }
        public static PedVoice GEN_BMOTR1 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BMOTR1"); } }
        public static PedVoice GEN_BMYAP { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BMYAP"); } }
        public static PedVoice GEN_BMYBE { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BMYBE"); } }
        public static PedVoice GEN_BMYBOUN { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BMYBOUN"); } }
        public static PedVoice GEN_BMYBOX { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BMYBOX"); } }
        public static PedVoice GEN_BMYBU { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BMYBU"); } }
        public static PedVoice GEN_BMYCG { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BMYCG"); } }
        public static PedVoice GEN_BMYCON { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BMYCON"); } }
        public static PedVoice GEN_BMYCR { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BMYCR"); } }
        public static PedVoice GEN_BMYDJ { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BMYDJ"); } }
        public static PedVoice GEN_BMYDRUG { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BMYDRUG"); } }
        public static PedVoice GEN_BMYMOUN { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BMYMOUN"); } }
        public static PedVoice GEN_BMYPOL1 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BMYPOL1"); } }
        public static PedVoice GEN_BMYPOL2 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BMYPOL2"); } }
        public static PedVoice GEN_BMYRI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BMYRI"); } }
        public static PedVoice GEN_BMYST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BMYST"); } }
        public static PedVoice GEN_BYMPI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_BYMPI"); } }
        public static PedVoice GEN_CWFOFR { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_CWFOFR"); } }
        public static PedVoice GEN_CWFOHB { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_CWFOHB"); } }
        public static PedVoice GEN_CWFYFR1 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_CWFYFR1"); } }
        public static PedVoice GEN_CWFYFR2 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_CWFYFR2"); } }
        public static PedVoice GEN_CWFYHB1 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_CWFYHB1"); } }
        public static PedVoice GEN_CWMOFR1 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_CWMOFR1"); } }
        public static PedVoice GEN_CWMOHB1 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_CWMOHB1"); } }
        public static PedVoice GEN_CWMOHB2 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_CWMOHB2"); } }
        public static PedVoice GEN_CWMYFR { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_CWMYFR"); } }
        public static PedVoice GEN_CWMYHB1 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_CWMYHB1"); } }
        public static PedVoice GEN_CWMYHB2 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_CWMYHB2"); } }
        public static PedVoice GEN_DNFOLC1 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_DNFOLC1"); } }
        public static PedVoice GEN_DNFOLC2 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_DNFOLC2"); } }
        public static PedVoice GEN_DNFYLC { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_DNFYLC"); } }
        public static PedVoice GEN_DNMOLC1 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_DNMOLC1"); } }
        public static PedVoice GEN_DNMOLC2 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_DNMOLC2"); } }
        public static PedVoice GEN_DNMYLC { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_DNMYLC"); } }
        public static PedVoice GEN_DWFOLC { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_DWFOLC"); } }
        public static PedVoice GEN_DWFYLC1 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_DWFYLC1"); } }
        public static PedVoice GEN_DWFYLC2 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_DWFYLC2"); } }
        public static PedVoice GEN_DWMOLC1 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_DWMOLC1"); } }
        public static PedVoice GEN_DWMOLC2 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_DWMOLC2"); } }
        public static PedVoice GEN_DWMYLC1 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_DWMYLC1"); } }
        public static PedVoice GEN_DWMYLC2 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_DWMYLC2"); } }
        public static PedVoice GEN_HFORI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_HFORI"); } }
        public static PedVoice GEN_HFOST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_HFOST"); } }
        public static PedVoice GEN_HFYBE { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_HFYBE"); } }
        public static PedVoice GEN_HFYPRO { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_HFYPRO"); } }
        public static PedVoice GEN_HFYRI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_HFYRI"); } }
        public static PedVoice GEN_HFYST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_HFYST"); } }
        public static PedVoice GEN_HMORI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_HMORI"); } }
        public static PedVoice GEN_HMOST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_HMOST"); } }
        public static PedVoice GEN_HMYBE { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_HMYBE"); } }
        public static PedVoice GEN_HMYCM { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_HMYCM"); } }
        public static PedVoice GEN_HMYCR { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_HMYCR"); } }
        public static PedVoice GEN_HMYDRUG { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_HMYDRUG"); } }
        public static PedVoice GEN_HMYRI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_HMYRI"); } }
        public static PedVoice GEN_HMYST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_HMYST"); } }
        public static PedVoice GEN_IMYST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_IMYST"); } }
        public static PedVoice GEN_IRFYST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_IRFYST"); } }
        public static PedVoice GEN_IRMYST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_IRMYST"); } }
        public static PedVoice GEN_MAFFA { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_MAFFA"); } }
        public static PedVoice GEN_MAFFB { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_MAFFB"); } }
        public static PedVoice GEN_MALE01 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_MALE01"); } }
        public static PedVoice GEN_NOVOICE { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_NOVOICE"); } }
        public static PedVoice GEN_OFORI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_OFORI"); } }
        public static PedVoice GEN_OFOST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_OFOST"); } }
        public static PedVoice GEN_OFYRI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_OFYRI"); } }
        public static PedVoice GEN_OFYST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_OFYST"); } }
        public static PedVoice GEN_OMOBOAT { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_OMOBOAT"); } }
        public static PedVoice GEN_OMOKUNG { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_OMOKUNG"); } }
        public static PedVoice GEN_OMORI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_OMORI"); } }
        public static PedVoice GEN_OMOST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_OMOST"); } }
        public static PedVoice GEN_OMYRI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_OMYRI"); } }
        public static PedVoice GEN_OMYST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_OMYST"); } }
        public static PedVoice GEN_SBFORI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SBFORI"); } }
        public static PedVoice GEN_SBFOST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SBFOST"); } }
        public static PedVoice GEN_SBFYPRO { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SBFYPRO"); } }
        public static PedVoice GEN_SBFYRI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SBFYRI"); } }
        public static PedVoice GEN_SBFYST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SBFYST"); } }
        public static PedVoice GEN_SBFYSTR { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SBFYSTR"); } }
        public static PedVoice GEN_SBMOCD { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SBMOCD"); } }
        public static PedVoice GEN_SBMORI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SBMORI"); } }
        public static PedVoice GEN_SBMOST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SBMOST"); } }
        public static PedVoice GEN_SBMOTR1 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SBMOTR1"); } }
        public static PedVoice GEN_SBMOTR2 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SBMOTR2"); } }
        public static PedVoice GEN_SBMYCR { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SBMYCR"); } }
        public static PedVoice GEN_SBMYRI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SBMYRI"); } }
        public static PedVoice GEN_SBMYST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SBMYST"); } }
        public static PedVoice GEN_SBMYTR3 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SBMYTR3"); } }
        public static PedVoice GEN_SFYPRO { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SFYPRO"); } }
        public static PedVoice GEN_SHFYPRO { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SHFYPRO"); } }
        public static PedVoice GEN_SHMYCR { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SHMYCR"); } }
        public static PedVoice GEN_SMYST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SMYST"); } }
        public static PedVoice GEN_SMYST2 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SMYST2"); } }
        public static PedVoice GEN_SOFORI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SOFORI"); } }
        public static PedVoice GEN_SOFOST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SOFOST"); } }
        public static PedVoice GEN_SOFYBU { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SOFYBU"); } }
        public static PedVoice GEN_SOFYRI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SOFYRI"); } }
        public static PedVoice GEN_SOFYST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SOFYST"); } }
        public static PedVoice GEN_SOMOBU { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SOMOBU"); } }
        public static PedVoice GEN_SOMORI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SOMORI"); } }
        public static PedVoice GEN_SOMOST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SOMOST"); } }
        public static PedVoice GEN_SOMYAP { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SOMYAP"); } }
        public static PedVoice GEN_SOMYBU { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SOMYBU"); } }
        public static PedVoice GEN_SOMYRI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SOMYRI"); } }
        public static PedVoice GEN_SOMYST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SOMYST"); } }
        public static PedVoice GEN_SWFOPRO { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SWFOPRO"); } }
        public static PedVoice GEN_SWFORI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SWFORI"); } }
        public static PedVoice GEN_SWFOST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SWFOST"); } }
        public static PedVoice GEN_SWFYRI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SWFYRI"); } }
        public static PedVoice GEN_SWFYST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SWFYST"); } }
        public static PedVoice GEN_SWFYSTR { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SWFYSTR"); } }
        public static PedVoice GEN_SWMOCD { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SWMOCD"); } }
        public static PedVoice GEN_SWMORI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SWMORI"); } }
        public static PedVoice GEN_SWMOST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SWMOST"); } }
        public static PedVoice GEN_SWMOTR1 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SWMOTR1"); } }
        public static PedVoice GEN_SWMOTR2 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SWMOTR2"); } }
        public static PedVoice GEN_SWMOTR3 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SWMOTR3"); } }
        public static PedVoice GEN_SWMOTR4 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SWMOTR4"); } }
        public static PedVoice GEN_SWMOTR5 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SWMOTR5"); } }
        public static PedVoice GEN_SWMYCR { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SWMYCR"); } }
        public static PedVoice GEN_SWMYHP1 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SWMYHP1"); } }
        public static PedVoice GEN_SWMYHP2 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SWMYHP2"); } }
        public static PedVoice GEN_SWMYRI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SWMYRI"); } }
        public static PedVoice GEN_SWMYST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_SWMYST"); } }
        public static PedVoice GEN_VBFYPRO { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_VBFYPRO"); } }
        public static PedVoice GEN_VBFYST2 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_VBFYST2"); } }
        public static PedVoice GEN_VBMOCD { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_VBMOCD"); } }
        public static PedVoice GEN_VBMYCR { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_VBMYCR"); } }
        public static PedVoice GEN_VBMYELV { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_VBMYELV"); } }
        public static PedVoice GEN_VHFYPRO { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_VHFYPRO"); } }
        public static PedVoice GEN_VHFYST3 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_VHFYST3"); } }
        public static PedVoice GEN_VHMYCR { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_VHMYCR"); } }
        public static PedVoice GEN_VHMYELV { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_VHMYELV"); } }
        public static PedVoice GEN_VIMYELV { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_VIMYELV"); } }
        public static PedVoice GEN_VWFYPRO { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_VWFYPRO"); } }
        public static PedVoice GEN_VWFYST1 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_VWFYST1"); } }
        public static PedVoice GEN_VWFYWAI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_VWFYWAI"); } }
        public static PedVoice GEN_VWMOTR1 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_VWMOTR1"); } }
        public static PedVoice GEN_VWMOTR2 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_VWMOTR2"); } }
        public static PedVoice GEN_VWMYAP { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_VWMYAP"); } }
        public static PedVoice GEN_VWMYBJD { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_VWMYBJD"); } }
        public static PedVoice GEN_VWMYCD { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_VWMYCD"); } }
        public static PedVoice GEN_VWMYCR { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_VWMYCR"); } }
        public static PedVoice GEN_WFOPJ { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WFOPJ"); } }
        public static PedVoice GEN_WFORI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WFORI"); } }
        public static PedVoice GEN_WFOST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WFOST"); } }
        public static PedVoice GEN_WFYBE { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WFYBE"); } }
        public static PedVoice GEN_WFYBU { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WFYBU"); } }
        public static PedVoice GEN_WFYCRK { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WFYCRK"); } }
        public static PedVoice GEN_WFYCRP { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WFYCRP"); } }
        public static PedVoice GEN_WFYJG { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WFYJG"); } }
        public static PedVoice GEN_WFYLG { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WFYLG"); } }
        public static PedVoice GEN_WFYPRO { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WFYPRO"); } }
        public static PedVoice GEN_WFYRI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WFYRI"); } }
        public static PedVoice GEN_WFYRO { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WFYRO"); } }
        public static PedVoice GEN_WFYST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WFYST"); } }
        public static PedVoice GEN_WFYSTEW { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WFYSTEW"); } }
        public static PedVoice GEN_WMOMIB { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMOMIB"); } }
        public static PedVoice GEN_WMOPJ { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMOPJ"); } }
        public static PedVoice GEN_WMOPREA { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMOPREA"); } }
        public static PedVoice GEN_WMORI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMORI"); } }
        public static PedVoice GEN_WMOSCI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMOSCI"); } }
        public static PedVoice GEN_WMOST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMOST"); } }
        public static PedVoice GEN_WMOTR1 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMOTR1"); } }
        public static PedVoice GEN_WMYBE { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYBE"); } }
        public static PedVoice GEN_WMYBMX { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYBMX"); } }
        public static PedVoice GEN_WMYBOUN { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYBOUN"); } }
        public static PedVoice GEN_WMYBOX { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYBOX"); } }
        public static PedVoice GEN_WMYBP { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYBP"); } }
        public static PedVoice GEN_WMYBU { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYBU"); } }
        public static PedVoice GEN_WMYCD1 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYCD1"); } }
        public static PedVoice GEN_WMYCD2 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYCD2"); } }
        public static PedVoice GEN_WMYCH { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYCH"); } }
        public static PedVoice GEN_WMYCON { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYCON"); } }
        public static PedVoice GEN_WMYCONB { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYCONB"); } }
        public static PedVoice GEN_WMYCR { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYCR"); } }
        public static PedVoice GEN_WMYDRUG { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYDRUG"); } }
        public static PedVoice GEN_WMYGAR { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYGAR"); } }
        public static PedVoice GEN_WMYGOL1 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYGOL1"); } }
        public static PedVoice GEN_WMYGOL2 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYGOL2"); } }
        public static PedVoice GEN_WMYJG { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYJG"); } }
        public static PedVoice GEN_WMYLG { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYLG"); } }
        public static PedVoice GEN_WMYMECH { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYMECH"); } }
        public static PedVoice GEN_WMYMOUN { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYMOUN"); } }
        public static PedVoice GEN_WMYPLT { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYPLT"); } }
        public static PedVoice GEN_WMYRI { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYRI"); } }
        public static PedVoice GEN_WMYRO { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYRO"); } }
        public static PedVoice GEN_WMYSGRD { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYSGRD"); } }
        public static PedVoice GEN_WMYSKAT { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYSKAT"); } }
        public static PedVoice GEN_WMYST { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYST"); } }
        public static PedVoice GEN_WMYTX1 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYTX1"); } }
        public static PedVoice GEN_WMYTX2 { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYTX2"); } }
        public static PedVoice GEN_WMYVA { get { return new PedVoice("PED_TYPE_GEN", "VOICE_GEN_WMYVA"); } }
        public static PedVoice EMG_ARMY1 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_ARMY1"); } }
        public static PedVoice EMG_ARMY2 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_ARMY2"); } }
        public static PedVoice EMG_ARMY3 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_ARMY3"); } }
        public static PedVoice EMG_EMT1 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_EMT1"); } }
        public static PedVoice EMG_EMT2 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_EMT2"); } }
        public static PedVoice EMG_EMT3 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_EMT3"); } }
        public static PedVoice EMG_EMT4 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_EMT4"); } }
        public static PedVoice EMG_EMT5 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_EMT5"); } }
        public static PedVoice EMG_FBI2 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_FBI2"); } }
        public static PedVoice EMG_FBI3 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_FBI3"); } }
        public static PedVoice EMG_FBI4 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_FBI4"); } }
        public static PedVoice EMG_FBI5 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_FBI5"); } }
        public static PedVoice EMG_FBI6 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_FBI6"); } }
        public static PedVoice EMG_LAPD1 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_LAPD1"); } }
        public static PedVoice EMG_LAPD2 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_LAPD2"); } }
        public static PedVoice EMG_LAPD3 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_LAPD3"); } }
        public static PedVoice EMG_LAPD4 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_LAPD4"); } }
        public static PedVoice EMG_LAPD5 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_LAPD5"); } }
        public static PedVoice EMG_LAPD6 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_LAPD6"); } }
        public static PedVoice EMG_LAPD7 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_LAPD7"); } }
        public static PedVoice EMG_LAPD8 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_LAPD8"); } }
        public static PedVoice EMG_LVPD1 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_LVPD1"); } }
        public static PedVoice EMG_LVPD2 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_LVPD2"); } }
        public static PedVoice EMG_LVPD3 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_LVPD3"); } }
        public static PedVoice EMG_LVPD4 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_LVPD4"); } }
        public static PedVoice EMG_LVPD5 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_LVPD5"); } }
        public static PedVoice EMG_MCOP1 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_MCOP1"); } }
        public static PedVoice EMG_MCOP2 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_MCOP2"); } }
        public static PedVoice EMG_MCOP3 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_MCOP3"); } }
        public static PedVoice EMG_MCOP4 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_MCOP4"); } }
        public static PedVoice EMG_MCOP5 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_MCOP5"); } }
        public static PedVoice EMG_MCOP6 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_MCOP6"); } }
        public static PedVoice EMG_PULASKI { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_PULASKI"); } }
        public static PedVoice EMG_RCOP1 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_RCOP1"); } }
        public static PedVoice EMG_RCOP2 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_RCOP2"); } }
        public static PedVoice EMG_RCOP3 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_RCOP3"); } }
        public static PedVoice EMG_RCOP4 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_RCOP4"); } }
        public static PedVoice EMG_SFPD1 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_SFPD1"); } }
        public static PedVoice EMG_SFPD2 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_SFPD2"); } }
        public static PedVoice EMG_SFPD3 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_SFPD3"); } }
        public static PedVoice EMG_SFPD4 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_SFPD4"); } }
        public static PedVoice EMG_SFPD5 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_SFPD5"); } }
        public static PedVoice EMG_SWAT1 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_SWAT1"); } }
        public static PedVoice EMG_SWAT2 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_SWAT2"); } }
        public static PedVoice EMG_SWAT4 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_SWAT4"); } }
        public static PedVoice EMG_SWAT6 { get { return new PedVoice("PED_TYPE_EMG", "VOICE_EMG_SWAT6"); } }
        public static PedVoice PLY_AG { get { return new PedVoice("PED_TYPE_PLAYER", "VOICE_PLY_AG"); } }
        public static PedVoice PLY_AG2 { get { return new PedVoice("PED_TYPE_PLAYER", "VOICE_PLY_AG2"); } }
        public static PedVoice PLY_AR { get { return new PedVoice("PED_TYPE_PLAYER", "VOICE_PLY_AR"); } }
        public static PedVoice PLY_AR2 { get { return new PedVoice("PED_TYPE_PLAYER", "VOICE_PLY_AR2"); } }
        public static PedVoice PLY_CD { get { return new PedVoice("PED_TYPE_PLAYER", "VOICE_PLY_CD"); } }
        public static PedVoice PLY_CD2 { get { return new PedVoice("PED_TYPE_PLAYER", "VOICE_PLY_CD2"); } }
        public static PedVoice PLY_CF { get { return new PedVoice("PED_TYPE_PLAYER", "VOICE_PLY_CF"); } }
        public static PedVoice PLY_CF2 { get { return new PedVoice("PED_TYPE_PLAYER", "VOICE_PLY_CF2"); } }
        public static PedVoice PLY_CG { get { return new PedVoice("PED_TYPE_PLAYER", "VOICE_PLY_CG"); } }
        public static PedVoice PLY_CG2 { get { return new PedVoice("PED_TYPE_PLAYER", "VOICE_PLY_CG2"); } }
        public static PedVoice PLY_CR { get { return new PedVoice("PED_TYPE_PLAYER", "VOICE_PLY_CR"); } }
        public static PedVoice PLY_CR2 { get { return new PedVoice("PED_TYPE_PLAYER", "VOICE_PLY_CR2"); } }
        public static PedVoice PLY_PG { get { return new PedVoice("PED_TYPE_PLAYER", "VOICE_PLY_PG"); } }
        public static PedVoice PLY_PG2 { get { return new PedVoice("PED_TYPE_PLAYER", "VOICE_PLY_PG2"); } }
        public static PedVoice PLY_PR { get { return new PedVoice("PED_TYPE_PLAYER", "VOICE_PLY_PR"); } }
        public static PedVoice PLY_PR2 { get { return new PedVoice("PED_TYPE_PLAYER", "VOICE_PLY_PR2"); } }
        public static PedVoice PLY_WG { get { return new PedVoice("PED_TYPE_PLAYER", "VOICE_PLY_WG"); } }
        public static PedVoice PLY_WG2 { get { return new PedVoice("PED_TYPE_PLAYER", "VOICE_PLY_WG2"); } }
        public static PedVoice PLY_WR { get { return new PedVoice("PED_TYPE_PLAYER", "VOICE_PLY_WR"); } }
        public static PedVoice PLY_WR2 { get { return new PedVoice("PED_TYPE_PLAYER", "VOICE_PLY_WR2"); } }
        public static PedVoice GNG_BALLAS1 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_BALLAS1"); } }
        public static PedVoice GNG_BALLAS2 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_BALLAS2"); } }
        public static PedVoice GNG_BALLAS3 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_BALLAS3"); } }
        public static PedVoice GNG_BALLAS4 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_BALLAS4"); } }
        public static PedVoice GNG_BALLAS5 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_BALLAS5"); } }
        public static PedVoice GNG_BIG_BEAR { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_BIG_BEAR"); } }
        public static PedVoice GNG_CESAR { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_CESAR"); } }
        public static PedVoice GNG_DNB1 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_DNB1"); } }
        public static PedVoice GNG_DNB2 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_DNB2"); } }
        public static PedVoice GNG_DNB3 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_DNB3"); } }
        public static PedVoice GNG_DNB5 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_DNB5"); } }
        public static PedVoice GNG_DWAINE { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_DWAINE"); } }
        public static PedVoice GNG_FAM1 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_FAM1"); } }
        public static PedVoice GNG_FAM2 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_FAM2"); } }
        public static PedVoice GNG_FAM3 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_FAM3"); } }
        public static PedVoice GNG_FAM4 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_FAM4"); } }
        public static PedVoice GNG_FAM5 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_FAM5"); } }
        public static PedVoice GNG_JIZZY { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_JIZZY"); } }
        public static PedVoice GNG_LSV1 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_LSV1"); } }
        public static PedVoice GNG_LSV2 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_LSV2"); } }
        public static PedVoice GNG_LSV3 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_LSV3"); } }
        public static PedVoice GNG_LSV4 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_LSV4"); } }
        public static PedVoice GNG_LSV5 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_LSV5"); } }
        public static PedVoice GNG_MACCER { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_MACCER"); } }
        public static PedVoice GNG_MAFBOSS { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_MAFBOSS"); } }
        public static PedVoice GNG_OGLOC { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_OGLOC"); } }
        public static PedVoice GNG_RYDER { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_RYDER"); } }
        public static PedVoice GNG_SFR1 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_SFR1"); } }
        public static PedVoice GNG_SFR2 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_SFR2"); } }
        public static PedVoice GNG_SFR3 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_SFR3"); } }
        public static PedVoice GNG_SFR4 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_SFR4"); } }
        public static PedVoice GNG_SFR5 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_SFR5"); } }
        public static PedVoice GNG_SMOKE { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_SMOKE"); } }
        public static PedVoice GNG_STRI1 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_STRI1"); } }
        public static PedVoice GNG_STRI2 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_STRI2"); } }
        public static PedVoice GNG_STRI4 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_STRI4"); } }
        public static PedVoice GNG_STRI5 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_STRI5"); } }
        public static PedVoice GNG_SWEET { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_SWEET"); } }
        public static PedVoice GNG_TBONE { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_TBONE"); } }
        public static PedVoice GNG_TORENO { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_TORENO"); } }
        public static PedVoice GNG_TRUTH { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_TRUTH"); } }
        public static PedVoice GNG_VLA1 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_VLA1"); } }
        public static PedVoice GNG_VLA2 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_VLA2"); } }
        public static PedVoice GNG_VLA3 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_VLA3"); } }
        public static PedVoice GNG_VLA4 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_VLA4"); } }
        public static PedVoice GNG_VLA5 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_VLA5"); } }
        public static PedVoice GNG_VMAFF1 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_VMAFF1"); } }
        public static PedVoice GNG_VMAFF2 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_VMAFF2"); } }
        public static PedVoice GNG_VMAFF3 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_VMAFF3"); } }
        public static PedVoice GNG_VMAFF4 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_VMAFF4"); } }
        public static PedVoice GNG_VMAFF5 { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_VMAFF5"); } }
        public static PedVoice GNG_WOOZIE { get { return new PedVoice("PED_TYPE_GANG", "VOICE_GNG_WOOZIE"); } }
        public static PedVoice GFD_BARBARA { get { return new PedVoice("PED_TYPE_GFD", "VOICE_GFD_BARBARA"); } }
        public static PedVoice GFD_BMOBAR { get { return new PedVoice("PED_TYPE_GFD", "VOICE_GFD_BMOBAR"); } }
        public static PedVoice GFD_BMYBARB { get { return new PedVoice("PED_TYPE_GFD", "VOICE_GFD_BMYBARB"); } }
        public static PedVoice GFD_BMYTATT { get { return new PedVoice("PED_TYPE_GFD", "VOICE_GFD_BMYTATT"); } }
        public static PedVoice GFD_CATALINA { get { return new PedVoice("PED_TYPE_GFD", "VOICE_GFD_CATALINA"); } }
        public static PedVoice GFD_DENISE { get { return new PedVoice("PED_TYPE_GFD", "VOICE_GFD_DENISE"); } }
        public static PedVoice GFD_HELENA { get { return new PedVoice("PED_TYPE_GFD", "VOICE_GFD_HELENA"); } }
        public static PedVoice GFD_KATIE { get { return new PedVoice("PED_TYPE_GFD", "VOICE_GFD_KATIE"); } }
        public static PedVoice GFD_MICHELLE { get { return new PedVoice("PED_TYPE_GFD", "VOICE_GFD_MICHELLE"); } }
        public static PedVoice GFD_MILLIE { get { return new PedVoice("PED_TYPE_GFD", "VOICE_GFD_MILLIE"); } }
        public static PedVoice GFD_POL_ANN { get { return new PedVoice("PED_TYPE_GFD", "VOICE_GFD_POL_ANN"); } }
        public static PedVoice GFD_WFYBURG { get { return new PedVoice("PED_TYPE_GFD", "VOICE_GFD_WFYBURG"); } }
        public static PedVoice GFD_WFYCLOT { get { return new PedVoice("PED_TYPE_GFD", "VOICE_GFD_WFYCLOT"); } }
        public static PedVoice GFD_WMYAMMO { get { return new PedVoice("PED_TYPE_GFD", "VOICE_GFD_WMYAMMO"); } }
        public static PedVoice GFD_WMYBARB { get { return new PedVoice("PED_TYPE_GFD", "VOICE_GFD_WMYBARB"); } }
        public static PedVoice GFD_WMYBELL { get { return new PedVoice("PED_TYPE_GFD", "VOICE_GFD_WMYBELL"); } }
        public static PedVoice GFD_WMYCLOT { get { return new PedVoice("PED_TYPE_GFD", "VOICE_GFD_WMYCLOT"); } }
        public static PedVoice GFD_WMYPIZZ { get { return new PedVoice("PED_TYPE_GFD", "VOICE_GFD_WMYPIZZ"); } }

        #endregion
    }
}
