-- Generated by CSharp.lua Compiler
local System = System

local Export = {}

Export.Invoke = function (resource, func, ...)
	local export = exports[resource]
	return export[func](export, ...)	
end

System.define("Slipe.Exports.Export", Export)