using System;
using System.Collections.Generic;
using System.Text;

namespace Slipe.Shared.Enums
{
    /// <summary>
    /// Represents different icons for map blips
    /// </summary>
    public enum BlipEnum
    {
        MARKER,
        WHITESQUARE,
        CENTRE,
        MAPHERE,
        NORTH,
        AIRYARD,
        GUN,
        BARBERS,
        BIGSMOKE ,
        BOATYARD,
        BURGERSHOT,
        BULLDOZER,
        CATPINK,
        CESAR,
        CHICKEN,
        CJ,
        CRASH,
        DINER,
        EMMETGUN,
        ENEMYATTACK,
        FIRE,
        GIRLFRIEND,
        HOSPITAL,
        LOCO,
        MADDDOG,
        MAFIA,
        MCSTRAP,
        MODGARAGE,
        OGLOC,
        PIZZA,
        POLICE,
        PROPERTYGREEN,
        PROPERTYRED ,
        RACE,
        RYDER,
        SAVEHOUSE,
        SCHOOl,
        MYSTERY,
        SWEET,
        TATTOO,
        TRUTH,
        WAYPOINT,
        TORENORANCH,
        TRIADS,
        TRIADSCASINO,
        TSHIRT,
        WOOZIE,
        ZERO,
        DATEDISCO,
        DATEDRINK,
        DATEFOOD,
        TRUCK,
        CASH,
        FLAG,
        GYM,
        IMPOUND,
        RUNWAYLIGHT,
        RUNWAY,
        GANGB,
        GANGP,
        GANGY,
        GANGN,
        GANGG,
        SPRAY
    }
}
