using System;
using System.Collections.Generic;
using System.Text;

namespace Slipe.Shared.Enums
{
    /// <summary>
    /// Reprents different garages around the world
    /// </summary>
    public enum GarageEnum
    {
        COMMERCE,
        LSPDIMPOUND,
        LOSDEPERADOS,
        EIGHTBALLAUTOS,
        CESARVIALPANDO,
        PROPERTYELCORONA,
        LSBURGLARYGARAGE,
        LOWRIDERTUNING,
        PAYNSPRAYIDLEWOOD,
        PROPERTYGANTON,
        TRANSFENDERTEMPLE,
        PAYNSPRAYTEMPLE,
        PAYNSPRAYSANTAMARIA,
        PROPERTYSANTAMARIA,
        PROPERTYMULHOLLAND,
        WHEELARCHANGELSOCEANFLATS,
        TBONEMENDEZ,
        PROPERTYGARAGEHASHBURY,
        TRANSFENDERDOHERTY,
        PAYNSPRAYDOWNTOWN,
        SFBURGLARYGARAGE,
        PROPERTYDOHERTY,
        MISSIONDOHERTY,
        RANFALI,
        MICHELLESPAYNSPRAY,
        PROPERTYCALTONHEIGHTS,
        SFPDIMPOUND,
        PAYNSPRAYJUNIPERHOLLOW,
        PROPERTYPARADISO,
        LVPDIMPOUND,
        AIRPORTHANGARLV,
        LVBURGLARY,
        PAYNSPRAYROYALCASINO,
        TRANSFENDERCOMEALOT,
        PROPERTYROCKSHOREWEST,
        WELDINGWEDDINGBOMB,
        PAYNSPRAYREDSANDSEAST,
        PROPERTYREDSANDSWEST,
        PROPERTYPRICKLEPINE,
        PROPERTYWHITEWOODESTATES,
        PAYNSPRAYELQUEBRADOS,
        PAYNSPRAYFORTCARSON,
        PROPERTYFORTCARSON,
        PROPERTYVERDANTMEADOWS,
        INTERDICTION,
        AIRPORTHANGERVERDANTMEADOWS,
        PUNCTUREWOUNDS,
        PAYNSPRAYDILLIMORE,
        PROPERTYPALOMINOCREEK,
        PROPERTYDILLIMORE
    }
}
