using System;
using System.Collections.Generic;
using System.Text;

namespace SlipeLua.Shared.Peds
{
    /// <summary>
    /// Represents different ped stats
    /// </summary>
    public enum PedStat
    {
        ProgressMade,
        TotalProgress,
        LongestBasketball,
        DistFoot,
        DistCar,
        DistBike,
        DistBoat,
        DistGolfCart,
        DistHelicopter,
        DistPlane,
        LongestWheelieDist,
        LongestStoppieDist,
        Longest2wheelDist,
        WeaponBudget,
        FashionBudget,
        PropertyBudget,
        SprayingBudget,
        LongestWheelieTime,
        LongestStoppieTime,
        Longest2wheelTime,
        FoodBudget,
        Fat,
        Stamina,
        BodyMuscle,
        MaxHealth,
        SexAppeal,
        DistSwimming,
        DistCycle,
        DistTreadmill,
        DistExcersiseBike,
        TattooBudget,
        HairdressingBudget,
        ProstituteBudget = 33,
        MoneySpentGambling = 35,
        MoneyMadePimping,
        MoneyWonGambling,
        BiggestGamblingWin,
        BiggestGamblingLoss,
        LargestBurglarySwag,
        MoneyMadeBurglary,
        LongestTreadmillTime = 44,
        LongestExcersiseBikeTime,
        HeaviestWeightBenchPress,
        HeaviestWeightDumbells,
        BestTimeHotring,
        BestTimeBmx,
        LongestChaseTime,
        LastChaseTime,
        WageBill,
        StripClubBudget,
        CarModBudget,
        TimeSpentShopping,
        TotalShoppingBudget = 62,
        TimeSpentUnderwater,
        RespectTotal,
        RespectGirlfriend,
        RespectClothes,
        RespectFitness,
        Respect,
        WeapontypePistolSkill,
        WeapontypePistolSilencedSkill,
        WeapontypeDesertEagleSkill,
        WeapontypeShotgunSkill,
        WeapontypeSawnoffShotgunSkill,
        WeapontypeSpas12ShotgunSkill,
        WeapontypeMicroUziSkill,
        WeapontypeMp5Skill,
        WeapontypeAk47Skill,
        WeapontypeM4Skill,
        WeapontypeSniperrifleSkill,
        SexAppealClothes,
        Gambling,
        PeopleKilledByOthers = 120,
        PeopleKilledByPlayer,
        CarsDestroyed,
        BoatsDestroyed,
        HelicoptorsDestroyed,
        PropertyDestroyed,
        RoundsFired,
        ExplosivesUsed,
        BulletsHit,
        TyresPopped,
        HeadsPopped,
        WantedStarsAttained,
        WantedStarsEvaded,
        TimesArrested,
        DaysPassed,
        TimesDied,
        TimesSaved,
        TimesCheated,
        Sprayings,
        MaxJumpDistance,
        MaxJumpHeight,
        MaxJumpFlips,
        MaxJumpSpins,
        BestStunt,
        UniqueJumpsFound,
        UniqueJumpsDone,
        MissionsAttempted,
        MissionsPassed,
        TotalMissions,
        TaxiMoneyMade,
        PassengersDeliveredInTaxi,
        LivesSaved,
        CriminalsCaught,
        FiresExtinguished,
        PizzasDelivered,
        Assassinations,
        LatestDanceScore,
        VigilanteLevel,
        AmbulanceLevel,
        FirefighterLevel,
        DrivingSkill,
        TruckMissionsPassed,
        TruckMoneyMade,
        RecruitedGangMembersKilled,
        Armour,
        Energy,
        PhotosTaken,
        KillFrenziesAttempted,
        KillFrenziesPassed,
        FlightTime,
        TimesDrowned,
        NumGirlsPimped,
        BestPositionHotring,
        FlightTimeJetpack,
        ShootingRangeScore,
        ValetCarsParked,
        KillsSinceLastCheckpoint,
        TotalLegitimateKills,
        BloodringKills,
        BloodringTime,
        NoMoreHurricanes,
        CitiesPassed,
        PoliceBribes,
        CarsStolen,
        CurrentGirlfriends,
        BadDates,
        GirlsDated,
        TimesScoredWithGirl,
        Dates,
        GirlsDumped,
        TimesVisitedProstitute,
        HousesBurgled,
        SafesCracked,
        StolenItemsSold = 194,
        EightBallsInPool,
        WinsInPool,
        LossesInPool,
        VisitsToGym,
        MealsEaten = 200,
        UnderwaterStamina = 225,
        BikeSkill = 229,
        CycleSkill
    }
}
