using System;
using System.Collections.Generic;
using System.Text;

namespace Slipe.Shared.Enums
{
    /// <summary>
    /// Represents different icons for map blips
    /// </summary>
    public enum BlipEnum
    {
        MARKER = 0,
        WHITESQUARE = 1,
        CENTRE = 2,
        MAPHERE = 3,
        NORTH = 4,
        AIRYARD = 5,
        GUN = 6,
        BARBERS = 7,
        BIGSMOKE = 8,
        BOATYARD = 9,
        BURGERSHOT = 10,
        BULLDOZER = 11,
        CATPINK = 12,
        CESAR = 13,
        CHICKEN = 14,
        CJ = 15,
        CRASH = 16,
        DINER = 17,
        EMMETGUN = 18,
        ENEMYATTACK = 19,
        FIRE = 20,
        GIRLFRIEND = 21,
        HOSPITAL = 22,
        LOCO = 23,
        MADDDOG = 24,
        MAFIA = 25,
        MCSTRAP = 26,
        MODGARAGE = 27,
        OGLOC = 28,
        PIZZA = 29,
        POLICE = 30,
        PROPERTYGREEN = 31,
        PROPERTYRED = 32,
        RACE = 33,
        RYDER = 34,
        SAVEHOUSE = 35,
        SCHOOl = 36,
        MYSTERY = 37,
        SWEET = 38,
        TATTOO = 39,
        TRUTH = 40,
        WAYPOINT = 41,
        TORENORANCH = 42,
        TRIADS = 43,
        TRIADSCASINO = 44,
        TSHIRT = 45,
        WOOZIE = 46,
        ZERO = 47,
        DATEDISCO = 48,
        DATEDRINK = 49,
        DATEFOOD = 50,
        TRUCK = 51,
        CASH = 52,
        FLAG = 53,
        GYM = 54,
        IMPOUND = 55,
        RUNWAYLIGHT = 56,
        RUNWAY = 57,
        GANGB = 58,
        GANGP = 59,
        GANGY = 60,
        GANGN = 61,
        GANGG = 62,
        SPRAY = 63
    }
}
