-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Sql", function (namespace)
  namespace.class("MySqlConnectionString", function (namespace)
    local getDbName, setDbName, getHostname, setHostname, getPort, setPort, getUnix_socket, setUnix_socket, 
    getCharset, setCharset

    getDbName = function (this)
      return this.dbName
    end
    setDbName = function (this, value)
      this.dbName = value
    end

    getHostname = function (this)
      return this.hostname
    end
    setHostname = function (this, value)
      this.hostname = value
    end

    getPort = function (this)
      return this.port
    end
    setPort = function (this, value)
      this.port = value
    end

    getUnix_socket = function (this)
      return this.unixSocket
    end
    setUnix_socket = function (this, value)
      this.unixSocket = value
    end

    getCharset = function (this)
      return this.charset
    end
    setCharset = function (this, value)
      this.charset = value
    end

    return {
      getDbName = getDbName,
      setDbName = setDbName,
      getHostname = getHostname,
      setHostname = setHostname,
      getPort = getPort,
      setPort = setPort,
      getUnix_socket = getUnix_socket,
      setUnix_socket = setUnix_socket,
      getCharset = getCharset,
      setCharset = setCharset
    }
  end)
end)
