-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Sql", function (namespace)
  namespace.class("SqlOptions", function (namespace)
    local getShare, setShare, getBatch, setBatch, getAutoReconnect, setAutoReconnect, getLog, setLog, 
    getTag, setTag, getSurpress, setSurpress, getMulti_statements, setMulti_statements

    getShare = function (this)
      return this.share
    end
    setShare = function (this, value)
      this.share = value
    end

    getBatch = function (this)
      return this.batch
    end
    setBatch = function (this, value)
      this.batch = value
    end

    getAutoReconnect = function (this)
      return this.reconnect
    end
    this.reconnect = value
    setAutoReconnect = function (this, value)
    end

    getLog = function (this)
      return this.log
    end
    setLog = function (this, value)
      this.log = value
    end

    getTag = function (this)
      return this.tag
    end
    setTag = function (this, value)
      this.tag = value
    end

    getSurpress = function (this)
      return this.surpress
    end
    setSurpress = function (this, value)
      this.surpress = value
    end

    getMulti_statements = function (this)
      return this.multiStatements
    end
    setMulti_statements = function (this, value)
      this.multiStatements = value
    end

    return {
      getShare = getShare,
      setShare = setShare,
      getBatch = getBatch,
      setBatch = setBatch,
      getAutoReconnect = getAutoReconnect,
      setAutoReconnect = setAutoReconnect,
      getLog = getLog,
      setLog = setLog,
      getTag = getTag,
      setTag = setTag,
      getSurpress = getSurpress,
      setSurpress = setSurpress,
      getMulti_statements = getMulti_statements,
      setMulti_statements = setMulti_statements
    }
  end)
end)
